---
title: "Mike Fuller"

output: 
  pdf_document:
geometry: margin=1in
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)

```
\begin{center}
Toledo, OH | 616-953-0307 | mrfuller460@gmail.com | mikerfuller.com | linkedin.com/in/mfuller69 | github.com/mr-fuller | public.tableau.com/profile/mikerfuller | he/him
\end{center}

## Relevant Experience
##### Toledo Metropolitan Area Council of Governments, Toledo, OH, Transportation Planner, May 2015-January 2025
* Developed python script that saved weeks of staff time for regional crash analysis report
* Developed ArcGIS Online app that saved $54,000 for a project with a budget of $22,000
* Developed RShiny demographics dashboard website for an economic development group
* Developed python scripts to update files in ArcGIS Online with ArcGIS API for Python
* Created and maintained organization web map gallery and open data site in ArcGIS Online
* Provided demographic maps and analysis for major planning documents and ad hoc requests
* Collaborated on RFP development, proposal evaluation, and contract selection for statewide ridesharing software
* Develop ArcGIS Dashboard of demographic information as a resource for Justice40 initiative
* Develop web apps to crowdsource public comments and data

##### Ohio GIS Conference Speaker, 2020
* Presented on geocoding fundamentals

##### Ohio GIS Conference Speaker, September 2018
* Presented work on analyzing and visualizing vehicle probe data with PostGIS and R

## Education
##### University of Toledo, Toledo, OH, Master of Arts in Geography, August 2013-May 2015
* ABT

##### Calvin College, Grand Rapids, MI, Bachelor of Science in Engineering, May 2013
* Civil and Environmental Concentration
* Math minor





